/*
*	Sistemas de Informação I
*	2009/2010 Semestre Inverno
*	Trabalho Prático (Parte II)
*	
*	Elaborado por:
*	Grupo 1
*	30896 – Ricardo Canto
*	31401 – Nuno Cancelo
*	33595 – Nuno Sousa
*/

USE Zhongyixue ;
GO

IF OBJECT_ID('SINTOMA_PACIENTE') IS NOT NULL BEGIN
	DROP TABLE SINTOMA_PACIENTE ;
END ;

IF OBJECT_ID('SINTOMA_PADRAO') IS NOT NULL BEGIN
	DROP TABLE SINTOMA_PADRAO ;
END ;

IF OBJECT_ID('PACIENTE_SINTOMA_TERAPEUTA') IS NOT NULL BEGIN
	DROP TABLE PACIENTE_SINTOMA_TERAPEUTA ;
END ;

IF OBJECT_ID('TERAPEUTA_ESPECIALIZACAO') IS NOT NULL BEGIN
	DROP TABLE TERAPEUTA_ESPECIALIZACAO ;
END ;

IF OBJECT_ID('TRATAMENTO_PADRAO') IS NOT NULL BEGIN
	DROP TABLE TRATAMENTO_PADRAO ;
END ;

IF OBJECT_ID('SINTOMA') IS NOT NULL BEGIN
	DROP TABLE SINTOMA ;
END ;

IF OBJECT_ID('CONSULTA_NAOPRESENCIAL') IS NOT NULL BEGIN
	DROP TABLE CONSULTA_NAOPRESENCIAL ;
END ;

IF OBJECT_ID('SESSAO') IS NOT NULL BEGIN
	DROP TABLE SESSAO ;
END ;

IF OBJECT_ID('PADRAO') IS NOT NULL BEGIN
	DROP TABLE PADRAO ;
END ;

IF OBJECT_ID('NAOPRESENCIAL') IS NOT NULL BEGIN
	DROP TABLE NAOPRESENCIAL ;
END ;

IF OBJECT_ID('PRESENCIAL') IS NOT NULL BEGIN
	DROP TABLE PRESENCIAL ;
END ;

IF OBJECT_ID('TRATAMENTO') IS NOT NULL BEGIN
	DROP TABLE TRATAMENTO ;
END ;

IF OBJECT_ID('ESPECIALIZACAO') IS NOT NULL BEGIN
	DROP TABLE ESPECIALIZACAO ;
END ;

IF OBJECT_ID('CONSULTA') IS NOT NULL BEGIN
	DROP TABLE CONSULTA ;
END ;

IF OBJECT_ID('PACIENTE') IS NOT NULL BEGIN
	DROP TABLE PACIENTE ;
END ;

IF OBJECT_ID('TERAPEUTA') IS NOT NULL BEGIN
	DROP TABLE TERAPEUTA ;
END ;

IF OBJECT_ID('PESSOA') IS NOT NULL BEGIN
	DROP TABLE PESSOA ;
END ;